import React from 'react'
import Head from 'next/head'

const FormRecored = () => {
  return (
    <div>
        <Head>
        <title>Form-records</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>Form Recored</div>
    </div>
  )
}

export default FormRecored