import React from 'react' 
import Head from 'next/head'

const Student = () => {
  return (

    <div>
        <Head>
        <title>Students</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        students
      </div>
    </div>
  )
}

export default Student